[project]
name = "cookit"
dynamic = ["version"]
description = "A toolkit for self use."
authors = [{ name = "LgCuwukii", email = "lgc2333@126.com" }]
dependencies = ["typing-extensions>=4.14.1"]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc2333/cookit"

[project.optional-dependencies]
common = ["fleep>=1.0.1"]

jinja = ["jinja2>=3.1.6"]

loguru = ["loguru>=0.7.3"]

nonebot-base = ["nonebot2>=2.5.0"]
nonebot-alconna = ["cookit[nonebot-base]", "nonebot-plugin-alconna>=0.62.0"]
nonebot-localstore = [
    "cookit[nonebot-base]",
    "nonebot-plugin-localstore>=0.7.4",
]
nonebot = ["cookit[nonebot-alconna,nonebot-localstore]"]

playwright = ["playwright>=1.60.0", "anyio>=4.13.0", "yarl>=1.24.2"]
pw = ["cookit[playwright]"]

pydantic = ["pydantic>=1.10.0,<3.0.0,!=2.5.0,!=2.5.1"]
pyd = ["cookit[pydantic]"]

all = ["cookit[common,jinja,loguru,nonebot,playwright,pydantic]"]

[dependency-groups]
dev = [
    "cookit[all]",
    "pytest>=9.1.0",
    "pytest-cov>=7.1.0",
    "pytest-asyncio>=1.4.0",
    "pytest-playwright-asyncio>=0.8.0",
    "nonebot2[all]>=2.5.0",
    "nonebug>=0.4.4",
    "nonebot-adapter-satori>=1.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "cookit/__init__.py"

[tool.pytest.ini_options]
addopts = ["--cov=cookit", "--cov-report=term-missing"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
